asc/urls.py
from django.urls import path
from . import views
app_name = 'asc'

urlpatterns = [
    path('', views.asc_list, name="asc_list"),
    path('<str:id>/detail/', views.asc_detail, name="asc_detail"),
    path('<str:id>/edit/', views.asc_edit, name="asc_edit"),
    path('<str:id>/attribution/', views.asc_attribution, name="asc_attributon"),
    path('<str:id>/attribution/<int:id_attr>/delete/', views.asc_attribution_delete, name="asc_attribution_delete"),
    path('create/', views.asc_create, name="asc_create"),
]

smsi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('personnels/', include('personnel.urls')),
    path('equipements/', include('equipement.urls')),
    path('attributions/', include('attribution.urls')),
    path('asc/', include('asc.urls')),
    path('districts/', include('district.urls')),
    path('', views.home, name='dashboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asc/models.py
from crum import get_current_user
from django.db import models
from personnel.models import Personnel
from district.models import Site
from django.urls import reverse


class Asc(models.Model):
    SEXE_CHOICES = (
        ('M', 'M'),
        ('F', 'F'),
    )

    TYPE_CHOICES = (
        ('titulaire', 'Titulaire'),
        ('remplaçante', 'Remplaçante')
    )
    identifiant = models.CharField(max_length=255, unique=True)
    ancien_id = models.CharField(max_length=60, unique=True, null=True, blank=True)
    nom = models.CharField(max_length=255)
    prenom = models.CharField(max_length=155)
    sexe = models.CharField(max_length=2, choices=SEXE_CHOICES)
    site = models.ForeignKey(Site, on_delete=models.PROTECT)
    type = models.CharField(max_length=255, choices=TYPE_CHOICES)
    contact = models.CharField(max_length=255, blank=True, null=True)
    photo = models.ImageField(upload_to='image/ASCs/', null=True, blank=True)
    created_by = models.ForeignKey(Personnel, on_delete=models.PROTECT, editable=False,
                                   related_name='%(class)s_created')
    updated_by = models.ForeignKey(Personnel, on_delete=models.PROTECT, editable=False,
                                   related_name='%(class)s_updated',
                                   null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.created_by = user
        self.updated_by = user
        super(Asc, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('asc:asc_detail', args=[
            self.identifiant
        ])

    class Meta:
        verbose_name_plural = 'Asc'

    def __str__(self):
        return f"{self.nom} {self.prenom}"

asc/forms.py
from django import forms
from .models import Asc


class AscForm(forms.ModelForm):

    class Meta:
        model = Asc
        fields = (
            'identifiant',
            'ancien_id',
            'nom',
            'prenom',
            'sexe',
            'site',
            'type',
            'contact',
            'photo',
            )

asc/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse
from asc.models import Asc
from attribution.forms import AttibutionForm
from district.utils import display_errors
from .forms import AscForm
from attribution.models import Attribution
from django.contrib import messages
from django.http import JsonResponse


@login_required
def asc_list(request):
    ascs = Asc.objects.all()
    form = AscForm()
    return render(request, 'asc/list_asc.html', {"ascs": ascs, "form": form})


@login_required
def asc_create(request):
    form = AscForm()
    if request.method == "POST":
        form = AscForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Opération effectuée avec succès')
        else:
            display_errors(request, form)
    return redirect('asc:asc_list')


@login_required
def asc_edit(request, id):
    asc = Asc.objects.get(identifiant=id)
    if request.method == "POST":
        form = AscForm(request.POST, request.FILES, instance=asc)
        if form.is_valid():
            form.save()
            messages.success(request, 'Opération effectuée avec succès')
        else:
            display_errors(request, form)
    return redirect('asc:asc_list')


@login_required
def asc_detail(request, id):
    asc = Asc.objects.get(identifiant=id)
    if request.is_ajax():
        data = {
            "id": asc.id,
            "identifiant": asc.identifiant,
            "ancien_id": asc.ancien_id,
            "nom": asc.nom,
            "prenom": asc.prenom,
            "sexe": asc.sexe,
            "site": str(asc.site.id),
            "type": asc.type,
            "contact": asc.contact,
            "photo": asc.photo.url if asc.photo else ""
        }
        return JsonResponse(data)
    attr_form = AttibutionForm()
    attrs = Attribution.objects.filter(asc_id=asc.id)
    return render(request, 'asc/detail_asc.html', {'asc': asc, 'attr_form': attr_form, 'attrs': attrs})


@login_required
def asc_attribution(request, id):
    form = AttibutionForm()
    asc = Asc.objects.get(identifiant=id)
    if request.method == "POST":
        form = AttibutionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Opération effectuée avec succès')
        else:
            display_errors(request, form)
    return redirect('asc:asc_detail', id=asc.identifiant)


@login_required
def asc_attribution_delete(request, id, id_attr):
    asc = Asc.objects.get(identifiant=id)
    attr = Attribution.objects.get(id=id_attr)
    attr.delete()
    messages.success(request, 'Opération effectuée avec succès')
    return redirect('asc:asc_detail', id=asc.identifiant)

asc/templates/asc/create_asc.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row mt-3 m-1">
        <div class="col-md-8 offset-2">
            <div class="card">
                <div class="card-body">
                    <form action="{% url 'asc:asc_create' %}" method="post">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="form-group col-md-6 mb-0">
                               {{ form.identifiant|as_crispy_field }}
                            </div>
                             <div class="form-group col-md-6 mb-0">
                                {{ form.photo|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                {{ form.nom|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                {{ form.prenom|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                {{ form.site|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                {{ form.sexe|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                 {{ form.type|as_crispy_field }}
                            </div>
                            <div class="form-group col-md-6 mb-0">
                                 {{ form.contact|as_crispy_field }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success float-right">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

asc/templates/asc/detail_asc.html
{% extends 'dashboard.html' %}
{% load static  %}
{% block content %}
    <div class="row mt-3 m-1">
        <div class="col-md-12">
            <div class="float-left">
                <a href="{% url 'asc:asc_list' %}" class="btn btn-outline-primary"><i class="fa fa-arrow-left"></i> Retour</a>
            </div>
            <div class="float-right mb-3">
                <button data-toggle="modal" data-target="#attribution-modal" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;Ajouter un équipement</button>
            </div>
        </div>
    </div>

    <div class="row m-1">
        <div class="col-md-3">
            <div class="card card-small mb-4 pt-3">
                <div class="card-header border-bottom text-center">
                    <div class="mb-3 mx-auto">
                        <img class="img-thumbnail" src="{% if asc.photo%}{{ asc.photo.url }}{% else %}/media/user.png{% endif %}" alt="User Avatar" width="110"> </div>
                    <h4 class="mb-0">{{ asc.nom }} {{ asc.prenom }}</h4>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item p-2">
                        <strong class="text-muted d-block mb-2">Identifiant</strong>
                        <span>{{ asc.identifiant }}</span>
                    </li>
                    <li class="list-group-item p-2">
                        <strong class="text-muted d-block mb-2">District</strong>
                        <span>{{ asc.site.district }}</span>
                    </li>
                    <li class="list-group-item p-2">
                        <strong class="text-muted d-block mb-2">Site</strong>
                        <span>{{ asc.site.libelle|capfirst }}</span>
                    </li>
                    <li class="list-group-item p-2">
                        <strong class="text-muted d-block mb-2">Type</strong>
                        <span>{{ asc.type|capfirst }}</span>
                    </li>
                    <li class="list-group-item p-2">
                        <strong class="text-muted d-block mb-2">Contact</strong>
                        <span>{{ asc.contact }}</span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    <div class="card-title mb-2">
                        <h3>Liste des équipements</h3>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-striped equipement-asc-table">
                        <thead>
                        <tr class="userstable_filter"></tr>
                        <tr>
                            <th>Equipement</th>
                            <th>Quantité</th>
                            <th>Date Attribution</th>
                            <th>A renouveller le</th>
                            <th class="noExport">Options</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for attr in attrs %}
                            <tr>
                                <td>{{ attr.equipement }}</td>
                                <td>{{ attr.quantity }}</td>
                                <td>{{ attr.date_attribution }}</td>
                                <td class="text-danger">{{ attr.date_renouvellement }}</td>
                                <td>
                                    <div class="text-center ">
                                        <a href="#" class="btn btn-outline-secondary"><i class="fa fa-eye"></i></a>&nbsp;
                                        <a href="#" data-id="{{ attr.id }}" class="btn btn-outline-primary attribution-rempla" data-target="#remplacement-modal" data-toggle="modal">
                                            <i class="fa fa-recycle"></i>
                                        </a>&nbsp;
                                        <a href="{% url 'asc:asc_attribution_delete' attr.asc.identifiant attr.id %}" class="btn btn-outline-danger delete" data-toggle="modal" data-target="#confirm-delete">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {% include  'asc/partials/attribution-modal.html' %}
    {% include  'asc/partials/remplacement-equipement-modal.html' %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'equipement/js/equipement.js' %}"></script>
    <script>
    $('.attribution-rempla').click(function(){
        let id = $(this).data('id')
        $.get(`/attributions/${id}/detail/`, function(response){
            console.log(response)
        })
    })
    </script>
{% endblock %}

asc/templates/asc/list_asc.html
{% extends 'dashboard.html' %}

{% block content %}
    <div class="row mt-3 m-1">
        <div class="col-md-12">
            <div class="float-right mb-3">
                <button data-toggle="modal" data-target="#add-asc-modal" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;Ajouter</button>
                {#                <a href="{% url 'asc:asc_create' %}" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;Ajouter</a>#}
            </div>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered table-striped asc-table">
                        <thead>
                        <tr class="userstable_filter"></tr>
                        <tr>
                            <th>Id</th>
                            <th>Nom & prenom(s)</th>
                            <th>Sexe</th>
                            <th>District</th>
                            <th>site</th>
                            <th>contact</th>
                            <th class="noExport">options</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for asc in ascs %}
                            <tr>
                                <td>{{ asc.identifiant }}</td>
                                <td>{{ asc.nom }} {{ asc.prenom }}</td>
                                <td>{{ asc.sexe }}</td>
                                <td>{{ asc.site.district }}</td>
                                <td>{{ asc.site }}</td>
                                <td>{{ asc.contact }}</td>
                                <td>
                                    <div class="text-center ">
                                        <a href="{{ asc.get_absolute_url }}" class="btn btn-outline-primary"><i class="fa fa-eye"></i></a>&nbsp;
                                        <a href="{% url 'asc:asc_edit' asc.identifiant %}" data-id="{{ asc.identifiant }}" class="btn btn-outline-secondary edit-asc" data-toggle="modal" data-target="#edit-asc-modal">
                                            <i class="fa fa-edit"></i>
                                        </a>&nbsp;
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {% include  'asc/partials/add-asc-modal.html' %}
    {% include  'asc/partials/edit-asc-modal.html' %}
{% endblock %}

{% block scripts %}
    <script>
        $(function(){
            $('.edit-asc').click(function(){
                let form_url = $(this).attr('href')
                let form = $("#edit-asc-modal form")
                form.attr('action', form_url)
                let id = $(this).data('id')
                $.get(`/asc/${id}/detail/`, function(response){

                    form.find('#id_identifiant').val(response.identifiant)
                    form.find('#id_ancien_id').val(response.ancien_id)
                    form.find('#id_nom').val(response.nom)
                    form.find('#id_prenom').val(response.prenom)
                    form.find('#id_contact').val(response.contact)

                    if(response.photo !== ""){
                        form.find('#photo').attr('src',response.photo)
                    }else{
                        form.find('#photo').attr('src', "/media/user.png")
                    }

                    form.find("#id_site option").each(function(){

                        let l1 = response['site'].toLowerCase()

                        let l2 = $(this).val().toLowerCase()

                        if(l1.localeCompare(l2) === 0){
                            $(this).attr('selected', 'selected')
                        }
                    })

                    form.find("#id_sexe option").each(function(){

                        let l1 = response['sexe'].toLowerCase()
                        let l2 = $(this).val().toLowerCase()

                        if(l1.localeCompare(l2) === 0){
                            $(this).attr('selected', 'selected')
                        }
                    })

                    form.find("#id_type option").each(function(){

                        let l1 = response['type'].toLowerCase()
                        let l2 = $(this).val().toLowerCase()

                        if(l1.localeCompare(l2) === 0){
                            $(this).attr('selected', 'selected')
                        }
                    })





                })
            })
        })
    </script>
{% endblock %}