asc/urls.py
from django.urls import path
from . import views
app_name = 'asc'

urlpatterns = [
    path('', views.asc_list, name="asc_list"),
    path('<str:id>/detail/', views.asc_detail, name="asc_detail"),
    path('<str:id>/edit/', views.asc_edit, name="asc_edit"),
    path('<str:id>/attribution/', views.asc_attribution, name="asc_attributon"),
    path('<str:id>/attribution/<int:id_attr>/delete/', views.asc_attribution_delete, name="asc_attribution_delete"),
    path('create/', views.asc_create, name="asc_create"),
]

district/urls.py
from django.urls import path
from . import views

app_name = "district"

urlpatterns = [
    path('sites/', views.site_list, name="site_list"),
    path('create/', views.site_create, name="site_create"),
    path('sites/<int:id>/detail/', views.site_detail, name="site_detail"),
    path('sites/<int:id>/edit/', views.site_edit, name="site_edit"),
]

equipement/urls.py
from django.urls import path
from . import views

app_name = "equipement"

urlpatterns = [
    path('', views.equipement_list, name="list"),
    path('create/', views.equipement_create, name="create"),
    path('<int:id>/edit/', views.equipement_edit, name="edit"),
    path('<int:id>/detail/', views.equipement_detail, name="detail"),
    path('<int:id>/approvisionement/detail/', views.approvisionement_list, name="approvisionement_list"),
    path('approvisionement/', views.approvisionement_create, name="appro_create"),
]

smsi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('personnels/', include('personnel.urls')),
    path('equipements/', include('equipement.urls')),
    path('attributions/', include('attribution.urls')),
    path('asc/', include('asc.urls')),
    path('districts/', include('district.urls')),
    path('', views.home, name='dashboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/delete_confirmation_modal.html
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
               Voulez-vous vraiment effectuer la suppression ?
            </div>
            <div class="modal-footer">
                <button class="btn btn-outline-accent" data-dismiss="modal">Annuler</button>
                <a href="#" class="btn btn-outline-danger supp">Supprimer</a>
            </div>
        </div>
    </div>
</div>

templates/partials/footer.html
<footer class="main-footer d-flex p-2 px-3 bg-white border-top">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Products</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
        </li>
    </ul>
    <span class="copyright ml-auto my-auto mr-2">Copyright © 2018
              <a href="https://designrevision.com" rel="nofollow">DesignRevision</a>
            </span>
</footer>

templates/partials/navbar.html
<nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">

    <form action="#" class="main-navbar__search w-100 d-none d-md-flex d-lg-flex" method="post">
        {% csrf_token %}
        {#                        <div class="input-group input-group-seamless ml-3">#}
        {#                            <div class="input-group-prepend">#}
        {#                                <div class="input-group-text">#}
        {#                                    <i class="fas fa-search"></i>#}
        {#                                </div>#}
        {#                            </div>#}
        {#                            <input class="navbar-search form-control" type="text" placeholder="Search for something..." aria-label="Search"> #}
        {#                        </div>#}


    </form>
    <ul class="navbar-nav flex-row">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="d-none d-md-inline-block lead">{{ request.user.username|capfirst }}</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-small">
                <a class="dropdown-item" href="#">
                    <i class="material-icons">&#xE7FD;</i>
                    Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item text-danger" href="{% url 'logout' %}">
                    <i class="material-icons text-danger">&#xE879;</i>
                    Déconnexion
                </a>
            </div>
        </li>
    </ul>
    <nav class="nav">
        <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
            <i class="material-icons">&#xE5D2;</i>
        </a>
    </nav>
</nav>

templates/partials/sidebar.html
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="{% url 'dashboard' %}" style="line-height: 25px;">
                <div class="d-table m-auto">
                    {#                  #<img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;" src="#" alt="...">#}
                    <span class="d-none d-md-inline ml-1">SMSI</span>
                </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>

    <div class="nav-wrapper">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">
                    <i class="material-icons">dashboard</i>
                    <span>Tableau de bord</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'district:site_list' %}">
                    <i class="material-icons">house</i>
                    <span>Sites</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'asc:asc_list' %}">
                    <i class="material-icons">event_note</i>
                    <span>ASC</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'equipement:list' %}">
                    <i class="material-icons">apps</i>
                    <span>Equipements</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i class="material-icons">input</i>
                    <span>Attribution</span>
                </a>
            </li>

        </ul>
    </div>
</aside>