asc/urls.py
from django.urls import path
from . import views
app_name = 'asc'

urlpatterns = [
    path('', views.asc_list, name="asc_list"),
    path('<str:id>/detail/', views.asc_detail, name="asc_detail"),
    path('<str:id>/edit/', views.asc_edit, name="asc_edit"),
    path('<str:id>/attribution/', views.asc_attribution, name="asc_attributon"),
    path('<str:id>/attribution/<int:id_attr>/delete/', views.asc_attribution_delete, name="asc_attribution_delete"),
    path('create/', views.asc_create, name="asc_create"),
]

smsi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('personnels/', include('personnel.urls')),
    path('equipements/', include('equipement.urls')),
    path('attributions/', include('attribution.urls')),
    path('asc/', include('asc.urls')),
    path('districts/', include('district.urls')),
    path('', views.home, name='dashboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asc/models.py
from crum import get_current_user
from django.db import models
from personnel.models import Personnel
from district.models import Site
from django.urls import reverse


class Asc(models.Model):
    SEXE_CHOICES = (
        ('M', 'M'),
        ('F', 'F'),
    )

    TYPE_CHOICES = (
        ('titulaire', 'Titulaire'),
        ('remplaçante', 'Remplaçante')
    )
    identifiant = models.CharField(max_length=255, unique=True)
    ancien_id = models.CharField(max_length=60, unique=True, null=True, blank=True)
    nom = models.CharField(max_length=255)
    prenom = models.CharField(max_length=155)
    sexe = models.CharField(max_length=2, choices=SEXE_CHOICES)
    site = models.ForeignKey(Site, on_delete=models.PROTECT)
    type = models.CharField(max_length=255, choices=TYPE_CHOICES)
    contact = models.CharField(max_length=255, blank=True, null=True)
    photo = models.ImageField(upload_to='image/ASCs/', null=True, blank=True)
    created_by = models.ForeignKey(Personnel, on_delete=models.PROTECT, editable=False,
                                   related_name='%(class)s_created')
    updated_by = models.ForeignKey(Personnel, on_delete=models.PROTECT, editable=False,
                                   related_name='%(class)s_updated',
                                   null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.created_by = user
        self.updated_by = user
        super(Asc, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('asc:asc_detail', args=[
            self.identifiant
        ])

    class Meta:
        verbose_name_plural = 'Asc'

    def __str__(self):
        return f"{self.nom} {self.prenom}"

asc/forms.py
from django import forms
from .models import Asc


class AscForm(forms.ModelForm):

    class Meta:
        model = Asc
        fields = (
            'identifiant',
            'ancien_id',
            'nom',
            'prenom',
            'sexe',
            'site',
            'type',
            'contact',
            'photo',
            )

asc/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse
from asc.models import Asc
from attribution.forms import AttibutionForm
from district.utils import display_errors
from .forms import AscForm
from attribution.models import Attribution
from django.contrib import messages
from django.http import JsonResponse


@login_required
def asc_list(request):
    ascs = Asc.objects.all()
    form = AscForm()
    return render(request, 'asc/list_asc.html', {"ascs": ascs, "form": form})


@login_required
def asc_create(request):
    form = AscForm()
    if request.method == "POST":
        form = AscForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Opération effectuée avec succès')
        else:
            display_errors(request, form)
    return redirect('asc:asc_list')


@login_required
def asc_edit(request, id):
    asc = Asc.objects.get(identifiant=id)
    if request.method == "POST":
        form = AscForm(request.POST, request.FILES, instance=asc)
        if form.is_valid():
            form.save()
            messages.success(request, 'Opération effectuée avec succès')
        else:
            display_errors(request, form)
    return redirect('asc:asc_list')


@login_required
def asc_detail(request, id):
    asc = Asc.objects.get(identifiant=id)
    if request.is_ajax():
        data = {
            "id": asc.id,
            "identifiant": asc.identifiant,
            "ancien_id": asc.ancien_id,
            "nom": asc.nom,
            "prenom": asc.prenom,
            "sexe": asc.sexe,
            "site": str(asc.site.id),
            "type": asc.type,
            "contact": asc.contact,
            "photo": asc.photo.url if asc.photo else ""
        }
        return JsonResponse(data)
    attr_form = AttibutionForm()
    attrs = Attribution.objects.filter(asc_id=asc.id)
    return render(request, 'asc/detail_asc.html', {'asc': asc, 'attr_form': attr_form, 'attrs': attrs})


@login_required
def asc_attribution(request, id):
    form = AttibutionForm()
    asc = Asc.objects.get(identifiant=id)
    if request.method == "POST":
        form = AttibutionForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Opération effectuée avec succès')
        else:
            display_errors(request, form)
    return redirect('asc:asc_detail', id=asc.identifiant)


@login_required
def asc_attribution_delete(request, id, id_attr):
    asc = Asc.objects.get(identifiant=id)
    attr = Attribution.objects.get(id=id_attr)
    attr.delete()
    messages.success(request, 'Opération effectuée avec succès')
    return redirect('asc:asc_detail', id=asc.identifiant)

asc/templates/asc/partials/add-asc-modal.html
{% load crispy_forms_tags %}
<div class="modal fade" tabindex="-1" role="dialog" id="add-asc-modal">
    <div class="modal-dialog modal-lg" role="document">
        <form action="{% url 'asc:asc_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Création de asc</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.identifiant|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.ancien_id|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.nom|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.prenom|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.site|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.sexe|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.type|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.contact|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-12 mb-0">
                            {{ form.photo|as_crispy_field }}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Enrégistrer</button>
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                </div>
            </div>
        </form>
    </div>
</div>

asc/templates/asc/partials/attribution-modal.html
{% load crispy_forms_tags %}
<div class="modal fade" tabindex="-1" role="dialog" id="attribution-modal">
    <div class="modal-dialog" role="document">
        <form action="{% url 'asc:asc_attributon' asc.identifiant %}" method="post">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Attribution de matériel</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="asc" value="{{ asc.id }}">
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ attr_form.equipement|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-12 mb-0">
                            {{ attr_form.quantity|as_crispy_field }}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Enrégistrer</button>
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                </div>
            </div>
        </form>
    </div>
</div>

asc/templates/asc/partials/edit-asc-modal.html
{% load crispy_forms_tags %}
<div class="modal fade" tabindex="-1" role="dialog" id="edit-asc-modal">
    <div class="modal-dialog modal-lg" role="document">
        <form action="#" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Edition de asc</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-2">
                            <img src="/media/user.png" alt="..." class="img-thumbnail" id="photo" width="110px" height="70px">
                        </div>
                        <div class="form-group col-md-6 mb-2">
                            {{ form.photo|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.identifiant|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.ancien_id|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.nom|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.prenom|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.site|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.sexe|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.type|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.contact|as_crispy_field }}
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Enrégistrer</button>
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                </div>
            </div>
        </form>
    </div>
</div>

asc/templates/asc/partials/remplacement-equipement-modal.html
{% load crispy_forms_tags %}
<div class="modal fade" tabindex="-1" role="dialog" id="remplacement-modal">
    <div class="modal-dialog" role="document">
        <form action="" method="post">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Remplacement de matériel</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Enrégistrer</button>
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                </div>
            </div>
        </form>
    </div>
</div>