asc/urls.py
from django.urls import path
from . import views
app_name = 'asc'

urlpatterns = [
    path('', views.asc_list, name="asc_list"),
    path('<str:id>/detail/', views.asc_detail, name="asc_detail"),
    path('<str:id>/edit/', views.asc_edit, name="asc_edit"),
    path('<str:id>/attribution/', views.asc_attribution, name="asc_attributon"),
    path('<str:id>/attribution/<int:id_attr>/delete/', views.asc_attribution_delete, name="asc_attribution_delete"),
    path('create/', views.asc_create, name="asc_create"),
]

equipement/urls.py
from django.urls import path
from . import views

app_name = "equipement"

urlpatterns = [
    path('', views.equipement_list, name="list"),
    path('create/', views.equipement_create, name="create"),
    path('<int:id>/edit/', views.equipement_edit, name="edit"),
    path('<int:id>/detail/', views.equipement_detail, name="detail"),
    path('<int:id>/approvisionement/detail/', views.approvisionement_list, name="approvisionement_list"),
    path('approvisionement/', views.approvisionement_create, name="appro_create"),
]

smsi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('personnels/', include('personnel.urls')),
    path('equipements/', include('equipement.urls')),
    path('attributions/', include('attribution.urls')),
    path('asc/', include('asc.urls')),
    path('districts/', include('district.urls')),
    path('', views.home, name='dashboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipement/models.py
from django.db import models
from personnel.models import Personnel
from crum import get_current_user


class Equipement(models.Model):
    PERIODE_CHOICES = (
        ('semaine', 'SEMAINE'),
        ('mois', 'MOIS'),
        ('annee', 'ANNEE')
    )
    libelle = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    quantity = models.PositiveIntegerField(editable=False, default=0)
    echeance = models.PositiveIntegerField()
    periode = models.CharField(max_length=255, choices=PERIODE_CHOICES)
    created_by = models.ForeignKey(Personnel, on_delete=models.PROTECT, editable=False,
                                   related_name='%(class)s_created')
    updated_by = models.ForeignKey(Personnel, on_delete=models.PROTECT, editable=False,
                                   related_name='%(class)s_updated',
                                   null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.libelle

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.created_by = user
        self.updated_by = user
        super(Equipement, self).save(*args, **kwargs)


class Approvisionnement(models.Model):
    equipement = models.ForeignKey(Equipement, on_delete=models.CASCADE)
    quantity_add = models.PositiveIntegerField()
    quantity_stock_debut = models.PositiveIntegerField(editable=False)
    quantity_stock_fin = models.PositiveIntegerField(editable=False)
    created_by = models.ForeignKey(Personnel, on_delete=models.PROTECT, editable=False,
                                   related_name='%(class)s_created')
    updated_by = models.ForeignKey(Personnel, on_delete=models.PROTECT, editable=False,
                                   related_name='%(class)s_updated',
                                   null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.created_by = user
        self.updated_by = user
        try:
            equipement = Equipement.objects.get(id=self.equipement.id)
        except Equipement.DoesNotExist:
            pass
        else:
            if self.id:
                app = Approvisionnement.objects.get(id=self.id)
                equipement.quantity -= app.quantity_add
            self.quantity_stock_debut = equipement.quantity
            equipement.quantity += self.quantity_add
            equipement.save()
            self.quantity_stock_fin = equipement.quantity

        super(Approvisionnement, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.equipement.libelle} approvisioné de {self.quantity_add}"

equipement/forms.py
from django import forms
from .models import Equipement, Approvisionnement
from django.core.exceptions import ValidationError


class EquipmentForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 2}), required=False)

    class Meta:
        model = Equipement
        fields = '__all__'

    def clean_libelle(self):
        libelle = self.cleaned_data['libelle']
        return libelle.lower()

    def clean_echeance(self):
        echeance = int(self.cleaned_data['echeance'])
        if echeance <= 0:
            raise ValidationError("l'écheance doit être supérieur à 0")
        return echeance


class ApproForm(forms.ModelForm):

    class Meta:
        model = Approvisionnement
        fields = ('equipement', 'quantity_add',)

equipement/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Equipement, Approvisionnement
from .forms import EquipmentForm, ApproForm
from django.contrib import messages
from district.utils import display_errors
from django.http import JsonResponse


@login_required
def equipement_list(request):
    eqps = Equipement.objects.all()
    form = EquipmentForm()
    appro_form = ApproForm()
    return render(request, 'equipement/equipement-list.html', {"eqps": eqps, "form": form, "appro_form": appro_form})


@login_required
def equipement_edit(request, id):
    equipement = Equipement.objects.get(id=id)
    if request.method == "POST":
        form = EquipmentForm(request.POST, instance=equipement)
        if form.is_valid():
            form.save()
            messages.success(request, 'Modification effectuer avec succès')
        else:
            display_errors(request, form)
    return redirect('equipement:list')


@login_required
def equipement_detail(request, id):
    equipement = Equipement.objects.get(id=id)
    if request.is_ajax():
        data = {
            "id": equipement.id,
            "libelle": equipement.libelle.capitalize(),
            "description": equipement.description,
            "quantity": equipement.quantity,
            "echeance": equipement.echeance,
            "periode": equipement.periode,
        }
        return JsonResponse(data)
    return redirect('equipement:list')


@login_required
def equipement_create(request):
    eqps = Equipement.objects.all()
    form = EquipmentForm()
    if request.method == "POST":
        form = EquipmentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Modification effectuer avec succès')
        else:
            display_errors(request, form)
    return redirect('equipement:list')


@login_required
def approvisionement_create(request):
    if request.method == "POST":
        form = ApproForm(request.POST)
        if form.is_valid():
            form.save()
    return redirect('equipement:list')


@login_required
def approvisionement_list(request, id):
    equipement = Equipement.objects.get(id=id)
    approvis = Approvisionnement.objects.filter(equipement_id=id).order_by('-created_at')
    return render(request, 'equipement/equipement-approvisionnement.html', locals())

equipement/templates/equipement/equipement-approvisionnement.html
{% extends 'dashboard.html' %}

{% block content %}
    <div class="row mt-3 m-1">
        <div class="col-md-12">
            <div class="float-left w-auto">
                <a href="{% url 'equipement:list' %}" class="btn btn-outline-primary mb-3"><i class="fa fa-arrow-left"></i> Retour</a>
            </div>
            <div class="float-right w-auto">
                <span>Hisotrique approvisionnement: </span><h3>{{ equipement.libelle|capfirst }}</h3>
            </div>
        </div>
        <div class="col-md-12">
            <table class="table table-bordered table-striped equipement-table">
                <thead>
                <tr class="userstable_filter"></tr>
                <tr>
                    <th>Quantité disponible <span class="small">(avant approvisionnement)</span></th>
                    <th>Quantité ajouté</th>
                    <th>Total après ajout</th>
                    <th>Date d'approvisionnement</th>
                </tr>
                </thead>
                <tbody>
                {% for app in approvis %}
                    <tr>
                        <td>{{ app.quantity_stock_debut }}</td>
                        <td>{{ app.quantity_add }}</td>
                        <td>{{ app.quantity_stock_fin }}</td>
                        <td>{{ app.created_at|date }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

equipement/templates/equipement/equipement-list.html
{% extends 'dashboard.html' %}
{% load static %}
{% block content %}
    <div class="row mt-3 m-1">
        <div class="col-md-12">
            <div class="float-right w-auto">
                 <button data-target="#approvisionement-add" data-toggle="modal" class="btn btn-outline-primary">Approvisionner</button>
                <button data-toggle="modal" data-target="#equipement-add" class="btn btn-outline-success"><i class="fa fa-plus"></i>&nbsp;Ajouter</button>
            </div>
        </div>
        <div class="col-md-12">
            <table class="table table-bordered table-striped equipement-table">
                <thead>
                <tr class="userstable_filter"></tr>
                <tr>
                    <th>Libelle</th>
                    <th>Quantité Disponible</th>
                    <th>Période de renouvellement</th>
                    <th class="noExport">Options</th>

                </tr>
                </thead>
                <tbody>
                {% for eqp in eqps %}
                    <tr>
                        <td>{{ eqp.libelle|capfirst }}</td>
                        <td>{{ eqp.quantity }}</td>
                        <td>{{ eqp.echeance }} {{ eqp.periode }}{% if eqp.periode != "mois" %}{{ eqp.echeance|pluralize }}{% endif %}</td>
                        <td>
                            <div class="text-center ">
                                <a href="{% url 'equipement:approvisionement_list' eqp.id %}" class="btn btn-outline-primary"><i class="fa fa-eye"></i></a>&nbsp;
                                <a href="{% url 'equipement:edit' eqp.id %}" data-id="{{ eqp.id }}" class="btn btn-outline-success eqp-edit" data-target="#equipement-edit" data-toggle="modal">
                                    <i class="fa fa-edit"></i>
                                </a>&nbsp;
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% include 'equipement/partials/equipement_add.html' %}
    {% include 'equipement/partials/equipement-modal-edit.html' %}
    {% include 'equipement/partials/approvisionement-add.html' %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'equipement/js/equipement.js' %}"></script>
{% endblock %}